'use client';
import {useState} from 'react';
export default function AiPanel({admin}:{admin:boolean}){
 const [message,setMessage]=useState(''),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[apiKey,setApiKey]=useState(''),[provider,setProvider]=useState('openai'),[model,setModel]=useState(''),[status,setStatus]=useState('لم تفحص الإعدادات');
 async function settings(){try{const r=await fetch('/api/ai/settings');const d=await r.json();if(!r.ok)throw Error(d.error);setStatus(d.configured?`المزود: ${d.provider} — الطراز: ${d.model} — آخر تحديث: ${d.updatedAt}`:'لم يحفظ مفتاح بعد');if(d.configured){setProvider(d.provider);setModel(d.model);}}catch(e){setMessage(e instanceof Error?e.message:'تعذر التحميل');}}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/ai/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,model,apiKey})});const d=await r.json();if(!r.ok)throw Error(d.error);setApiKey('');await settings();setMessage('حفظ المفتاح مشفراً على الخادم. لم يتم اختبار صلاحية المزود إلا عند إرسال سؤال.');}catch(e){setMessage(e instanceof Error?e.message:'تعذر الحفظ');}finally{setBusy(false);}}
 async function ask(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setAnswer('');try{const r=await fetch('/api/ai/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:f.get('question'),tool:f.get('tool'),consent:f.get('consent')==='on'})});const d=await r.json();if(!r.ok)throw Error(d.error);setAnswer(d.answer);setMessage('أداة قراءة فقط؛ لم تنفذ تعديلات.');}catch(e){setMessage(e instanceof Error?e.message:'تعذر الاتصال');}finally{setBusy(false);}}
 return <section dir="rtl" className="panel space-y-5"><h2>المساعد الداخلي</h2><p role="status">{message}</p><p>أدوات محددة للقراءة فقط ضمن صلاحياتك، دون SQL حر أو حذف أو تعديل مالي. إجابات المزود قد تخطئ؛ راجع السجلات. الحد 20 طلباً للحساب في الساعة.</p>
 {admin&&<><button onClick={()=>void settings()}>فحص الإعدادات المحفوظة</button><p>{status}</p><form className="fields" onSubmit={save}><label>المزود<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select></label><label>معرف طراز مفعل لدى المزود<input required value={model} onChange={e=>setModel(e.target.value)} maxLength={100}/></label><label>مفتاح جديد للمزود<input type="password" autoComplete="new-password" required minLength={10} maxLength={512} value={apiKey} onChange={e=>setApiKey(e.target.value)}/></label><p>يلزم APP_ENCRYPTION_KEY على الخادم. لا يمكن استرجاع المفتاح من الواجهة؛ إدخال مفتاح جديد يستبدل القديم.</p><button disabled={busy}>حفظ الإعدادات والمفتاح</button></form></>}
 <form className="fields" onSubmit={ask}><label>الأداة<select name="tool"><option value="leads_summary">ملخص مراحل العملاء المسموحين لي دون أسماء أو جوالات</option><option value="my_attendance">سجل حضوري فقط</option></select></label><label>السؤال<textarea name="question" required minLength={2} maxLength={2000}/></label><label><input name="consent" type="checkbox" required/>أوافق على إرسال السؤال ونتائج الأداة المحددة إلى المزود الخارجي، دون مستندات أو بيانات شخصية غير لازمة</label><button className="primary" disabled={busy}>إرسال</button></form><p className="whitespace-pre-wrap" role="status">{answer}</p></section>;
}
