'use client';
import {useState} from 'react';
import {serviceTypes,attendanceCalendar,localDay} from '@/lib/hr-policy';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
type Profile={user_id:string;name:string;job_title:string;department:string;leave_balance:number;schedule:{latitude:number;longitude:number;radius:number;maxAccuracy:number;start:string;end:string;grace:number;days:number[];timezone:string}};
type State={month:string;calendarLeaves:{user_id:string;type:string;status:string;start_date:string|null;end_date:string|null}[];userId:string;serverTime:string;profiles:Profile[];attendance:{user_id:string;work_day:string;check_in:string;check_out:string|null;late_minutes:number}[];requests:{id:string;user_id:string;name:string;type:keyof typeof serviceTypes;details:string;status:string;start_date:string|null;end_date:string|null;review_note:string|null}[];announcements:{id:string;title:string;details:string}[]};
export default function HrPanel({admin}:{admin:boolean}){
 const [state,setState]=useState<State|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[kind,setKind]=useState<keyof typeof serviceTypes>('leave'),[details,setDetails]=useState('');
 const [selected,setSelected]=useState<Profile|null>(null);
 const [month,setMonth]=useState(''),[calendarUser,setCalendarUser]=useState(''),[startDate,setStartDate]=useState(''),[endDate,setEndDate]=useState('');
 async function load(){try{const r=await fetch('/api/hr'+(month?'?month='+encodeURIComponent(month):''),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setState(d);setMonth(d.month);}catch(e){setMessage(e instanceof Error?e.message:'تعذر التحميل');}}
 async function send(data:unknown){setBusy(true);try{const r=await fetch('/api/hr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage('تم الحفظ');await load();return true;}catch(e){setMessage(e instanceof Error?e.message:'تعذر الحفظ');return false;}finally{setBusy(false);}}
 function punch(kind:'in'|'out'){
  if(!navigator.geolocation){setMessage('الموقع غير متاح على هذا الجهاز');return;}
  setBusy(true);navigator.geolocation.getCurrentPosition(p=>void send({action:'punch',id:crypto.randomUUID(),kind,point:{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}}),()=>{setBusy(false);setMessage('تعذر تحديد الموقع. اسمح بالوصول واستخدم HTTPS ثم حاول مجدداً.');},{enableHighAccuracy:true,maximumAge:0,timeout:15000});
 }
 async function profile(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),num=(k:string)=>Number(f.get(k));await send({action:'profile',data:{userId:f.get('userId'),jobTitle:f.get('jobTitle'),department:f.get('department'),leaveBalance:num('leaveBalance'),schedule:{latitude:num('latitude'),longitude:num('longitude'),radius:num('radius'),maxAccuracy:num('maxAccuracy'),start:f.get('start'),end:f.get('end'),grace:num('grace'),days:f.getAll('days').map(Number),timezone:f.get('timezone')}}});}
 const mine=state?.profiles.find(p=>p.user_id===state.userId);
 const calendarProfile=state?.profiles.find(p=>p.user_id===(calendarUser||state.userId));
 const calendar=state&&calendarProfile?attendanceCalendar(state.month,state.attendance.filter(a=>a.user_id===calendarProfile.user_id),state.calendarLeaves.filter(r=>r.user_id===calendarProfile.user_id),calendarProfile.schedule.days,localDay(new Date(state.serverTime),calendarProfile.schedule.timezone)):[];
 const labels:Record<string,string>={present:'حضور',late:'تأخير',leave:'إجازة معتمدة',off:'خارج أيام العمل',scheduled:'دوام مجدول',no_record:'لا يوجد تسجيل'};
 return <section dir="rtl" className="panel space-y-6"><h2>الموظفون والحضور والخدمات</h2><button onClick={()=>void load()} disabled={busy}>تحميل / تحديث ملفي والسجل</button><p role="status">{message}</p>
 <div className="stats"><div className="panel">وقت الخادم عند آخر تحديث<strong>{state?new Date(state.serverTime).toLocaleTimeString('ar-SA'):'—'}</strong></div><div className="panel">رصيد الإجازات المعتمد يدوياً<strong>{mine?.leave_balance??'غير مضبوط'}</strong></div></div>
 {mine?<p>{mine.name} — {mine.job_title} — {mine.department}<br/>الدوام {mine.schedule.start} إلى {mine.schedule.end} ({mine.schedule.timezone})، سماح {mine.schedule.grace} دقيقة. الموقع المسموح: {mine.schedule.latitude}, {mine.schedule.longitude} — نصف القطر {mine.schedule.radius} متر، الدقة القصوى {mine.schedule.maxAccuracy} متر.</p>:<p>لا يوجد ملف موظف مضبوط لحسابك بعد. على الإدارة ربط مستخدم CRM بالملف والدوام والموقع الحقيقي.</p>}
 <div className="flex gap-3"><button className="primary" disabled={busy||!mine} onClick={()=>punch('in')}>تسجيل حضور</button><button className="primary" disabled={busy||!mine} onClick={()=>punch('out')}>تسجيل انصراف</button></div><p>يُستخدم وقت الخادم. موقع المتصفح لا يمنع انتحال GPS بشكل كامل. الدوام الليلي وتصحيح السجل يحتاجان مراجعة الإدارة.</p>
 <h3>تقويم الحضور والإجازات</h3><label>الشهر<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button disabled={busy} onClick={()=>void load()}>عرض الشهر</button>
 {admin&&<label>موظف التقويم<select value={calendarUser} onChange={e=>setCalendarUser(e.target.value)}><option value="">حسابي</option>{state?.profiles.map(p=><option key={p.user_id} value={p.user_id}>{p.name}</option>)}</select></label>}
 <p>الشهر المعروض: {state?.month||'لم يحمل بعد'}. أيام العمل بحسب الإعداد الحالي؛ عدم التسجيل ليس حكماً بالغياب أو خصماً. رصيد الإجازة لا يتغير تلقائياً.</p>
 {calendar.length>0&&<div className="overflow-x-auto"><div className="grid min-w-[560px] grid-cols-7 gap-2" aria-label="تقويم الحضور">{['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'].map(d=><strong key={d}>{d}</strong>)}{Array.from({length:calendar[0].weekday},(_,i)=><div aria-hidden="true" key={'blank'+i}/>)}{calendar.map(d=><article key={d.day} className="rounded border p-2"><time dateTime={d.day}>{d.day.slice(-2)}</time><p>{labels[d.status]}</p>{d.lateMinutes>0&&<p>{d.lateMinutes} دقيقة بعد السماح</p>}{d.checkIn&&<p>حضور {new Date(d.checkIn).toLocaleTimeString('ar-SA',{timeZone:calendarProfile?.schedule.timezone})}</p>}{d.checkOut&&<p>انصراف {new Date(d.checkOut).toLocaleTimeString('ar-SA',{timeZone:calendarProfile?.schedule.timezone})}</p>}</article>)}</div></div>}
 <h3>سجل الحضور اليومي للشهر المعروض</h3><Table><TableHeader><TableRow>{['الموظف','اليوم','أول حضور','آخر انصراف','التأخير بعد السماح'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{state?.attendance.map(r=><TableRow key={r.user_id+r.work_day}><TableCell>{state.profiles.find(p=>p.user_id===r.user_id)?.name||r.user_id}</TableCell><TableCell>{r.work_day}</TableCell><TableCell>{new Date(r.check_in).toLocaleString('ar-SA')}</TableCell><TableCell>{r.check_out?new Date(r.check_out).toLocaleString('ar-SA'):'—'}</TableCell><TableCell>{r.late_minutes} دقيقة</TableCell></TableRow>)}</TableBody></Table>
 <form className="fields" onSubmit={async e=>{e.preventDefault();if(await send({action:'request',data:{id:crypto.randomUUID(),type:kind,details,...(kind==='leave'?{startDate,endDate}:{})}}))setDetails('');}}><h3>طلب خدمة موظف</h3><label>النوع<select value={kind} onChange={e=>setKind(e.target.value as keyof typeof serviceTypes)}>{Object.entries(serviceTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{kind==='leave'&&<><label>بداية الإجازة<input type="date" required value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>نهاية الإجازة<input type="date" required min={startDate} value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></>}<label>التفاصيل والتواريخ والمبالغ المطلوبة<textarea required minLength={5} maxLength={4000} value={details} onChange={e=>setDetails(e.target.value)}/></label><p>اعتماد إداري واحد مع تسجيل القرار؛ لا يرحّل مبالغ للمالية ولا يغيّر أرصدة الإجازات أو البصمات تلقائياً.</p><button disabled={busy}>إرسال الطلب</button></form>
 <Table><TableHeader><TableRow><TableHead>الموظف / الخدمة</TableHead><TableHead>التفاصيل</TableHead><TableHead>الحالة والإشعار</TableHead><TableHead>مراجعة</TableHead></TableRow></TableHeader><TableBody>{state?.requests.map(r=><TableRow key={r.id}><TableCell>{r.name} — {serviceTypes[r.type]}</TableCell><TableCell className="whitespace-normal">{r.details}{r.start_date&&<p>{r.start_date} — {r.end_date}</p>}</TableCell><TableCell>{({pending:'قيد المراجعة',approved:'معتمد',rejected:'مرفوض'} as Record<string,string>)[r.status]} {r.review_note}</TableCell><TableCell>{admin&&r.status==='pending'&&r.user_id!==state.userId&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send({action:'review',data:{id:r.id,status:f.get('status'),note:f.get('note')}});}}><input aria-label="ملاحظة الاعتماد" name="note" required minLength={3}/><select name="status" aria-label="القرار"><option value="approved">اعتماد</option><option value="rejected">رفض</option></select><button disabled={busy}>حفظ القرار</button></form>}</TableCell></TableRow>)}</TableBody></Table>
 <h3>الإعلانات</h3>{state?.announcements.map(a=><article key={a.id}><h4>{a.title}</h4><p>{a.details}</p></article>)}
 {admin&&<><h3>إدارة ملفات الموظفين والدوام — صلاحية الإدارة فقط</h3><select aria-label="تعديل ملف" onChange={e=>setSelected(state?.profiles.find(p=>p.user_id===e.target.value)||null)}><option value="">ملف جديد</option>{state?.profiles.map(p=><option key={p.user_id} value={p.user_id}>{p.name}</option>)}</select>
 <form key={selected?.user_id||'new'} onSubmit={profile} className="fields"><label>معرف مستخدم CRM (UUID)<input name="userId" required defaultValue={selected?.user_id}/></label><label>المسمى الوظيفي<input name="jobTitle" required defaultValue={selected?.job_title}/></label><label>القسم<input name="department" required defaultValue={selected?.department}/></label><label>رصيد إجازات يدوي<input name="leaveBalance" type="number" min="0" max="365" required defaultValue={selected?.leave_balance}/></label>
 {(['latitude','longitude','radius','maxAccuracy','grace'] as const).map((k,i)=><label key={k}>{['خط العرض','خط الطول','نصف القطر بالمتر','أقصى دقة بالمتر','السماح بالدقائق'][i]}<input name={k} type="number" step="any" required defaultValue={selected?.schedule[k]}/></label>)}
 <label>بداية الدوام<input name="start" type="time" required defaultValue={selected?.schedule.start}/></label><label>نهاية الدوام<input name="end" type="time" required defaultValue={selected?.schedule.end}/></label><label>المنطقة الزمنية IANA<input name="timezone" placeholder="Asia/Riyadh" required defaultValue={selected?.schedule.timezone}/></label><fieldset><legend>أيام العمل</legend>{['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'].map((d,i)=><label key={d}><input name="days" type="checkbox" value={i} defaultChecked={selected?.schedule.days.includes(i)}/>{d}</label>)}</fieldset><button disabled={busy}>حفظ الملف والدوام</button></form>
 <form className="fields" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send({action:'announcement',data:{title:f.get('title'),details:f.get('details')}});}}><h3>إعلان جديد</h3><label>العنوان<input name="title" required minLength={2}/></label><label>النص<textarea name="details" required minLength={2}/></label><button disabled={busy}>نشر الإعلان للموظفين</button></form></>}
 </section>;
}
