'use client';
import {useState} from 'react';
import {importFields,type Mapping} from '@/lib/lead-import';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
type Preview={row:number;status:string;errors:string[];raw:string[];lead:{name:string;phone:string;propertyOther:string}|null};
export default function ImportPanel({onSaved}:{onSaved:()=>void}){
 const [sheets,setSheets]=useState<{sheet:string;data:string[][]}[]>([]),[sheet,setSheet]=useState(0),[header,setHeader]=useState(0),[mapping,setMapping]=useState<Mapping>({}),[preview,setPreview]=useState<Preview[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false);
 const raw=sheets[sheet]?.data||[],headers=raw[header]||[],rows=raw.slice(header+1);
 function reset(){setPreview([]);setConfirmed(false);}
 async function open(file:File|undefined){if(!file)return;setBusy(true);reset();setSheets([]);try{if(file.size>2000000||!file.name.toLowerCase().endsWith('.xlsx'))throw Error('اختر ملف xlsx بحجم لا يتجاوز 2 ميجابايت');const {default:read}=await import('read-excel-file/browser');const workbook=await read(file);if(workbook.some(s=>s.data.length>1001||s.data.some(r=>r.length>100)))throw Error('الحد 1000 صف بيانات و100 عمود لكل ورقة؛ قسّم الملف دون فقد البيانات');setSheets(workbook.map(s=>({sheet:s.sheet,data:s.data.map(r=>r.map(c=>c instanceof Date?c.toISOString().slice(0,10):String(c??'')))})));setSheet(0);setHeader(0);setMapping({});setMessage('اختر الورقة وصف العناوين ثم اربط الأعمدة. لا يتم حفظ شيء قبل التأكيد.');}catch(e){setMessage(e instanceof Error?e.message:'تعذر قراءة الملف');}finally{setBusy(false);}}
 async function run(mode:'preview'|'commit'){setBusy(true);try{const r=await fetch('/api/leads/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows,mapping,mode,confirmed})});const d=await r.json();if(!r.ok)throw Error(d.error);setPreview(d.rows);if(mode==='commit'){setMessage(`تم استيراد ${d.inserted} عميل. بقيت الصفوف الأصلية والمعاينة دون تغيير.`);setConfirmed(false);onSaved();}else setMessage('المعاينة جاهزة. يتم إعادة فحص التكرار على الخادم عند الحفظ.');}catch(e){setMessage(e instanceof Error?e.message:'تعذر الاستيراد');}finally{setBusy(false);}}
 function download(){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify({sheet:sheets[sheet]?.sheet,header,mapping,rows:preview},null,2)],{type:'application/json'}));a.href=url;a.download='import-review.json';a.click();URL.revokeObjectURL(url);}
 return <section dir="rtl" className="panel space-y-4"><h2>استيراد العملاء من Excel</h2><p>أرقام الجوال السعودية تُوحّد للمقارنة. التكرار بحسب الجوال؛ لا يستبدل أي عميل موجود. الأعمدة غير المربوطة تُحفظ مع الصف الأصلي للعميل المستورد. الصفوف غير الصالحة لا تُحذف من الملف. صيغ Excel لا تُحسب؛ استخدم قيماً محفوظة.</p><input type="file" accept=".xlsx" aria-label="ملف العملاء" disabled={busy} onChange={e=>void open(e.target.files?.[0])}/><p role="status">{message}</p>
 {sheets.length>0&&<><label>الورقة<select value={sheet} onChange={e=>{setSheet(Number(e.target.value));setHeader(0);setMapping({});reset();}}>{sheets.map((s,i)=><option key={s.sheet} value={i}>{s.sheet}</option>)}</select></label><label>رقم صف العناوين<input type="number" min={1} max={raw.length} value={header+1} onChange={e=>{setHeader(Math.max(0,Number(e.target.value)-1));setMapping({});reset();}}/></label>
 <div className="fields">{Object.entries(importFields).map(([key,label])=><label key={key}>{label}<select value={mapping[key as keyof Mapping]??''} onChange={e=>{const next={...mapping};if(e.target.value==='')delete next[key as keyof Mapping];else next[key as keyof Mapping]=Number(e.target.value);setMapping(next);reset();}}><option value="">غير مربوط</option>{headers.map((h,i)=><option key={i} value={i}>{i+1}: {h||'بدون عنوان'}</option>)}</select></label>)}</div><button disabled={busy||!rows.length} onClick={()=>void run('preview')}>معاينة وفحص التكرار</button>
 <Table><TableHeader><TableRow><TableHead>الصف</TableHead>{headers.map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice(0,10).map((r,i)=><TableRow key={i}><TableCell>{header+i+2}</TableCell>{headers.map((_,c)=><TableCell key={c}>{r[c]}</TableCell>)}</TableRow>)}</TableBody></Table><p>معاينة أول 10 صفوف من {rows.length} — كل الصفوف تُفحص على الخادم.</p></>}
 {preview.length>0&&<><p>جاهز: {preview.filter(r=>r.status==='ready').length}، مكرر: {preview.filter(r=>r.status==='duplicate').length}، غير صالح: {preview.filter(r=>r.status==='invalid').length}</p><Table><TableHeader><TableRow><TableHead>الصف</TableHead><TableHead>الاسم / الجوال</TableHead><TableHead>النتيجة</TableHead></TableRow></TableHeader><TableBody>{preview.map(r=><TableRow key={r.row}><TableCell>{r.row+header+1}</TableCell><TableCell>{r.lead?.name} {r.lead?.phone}</TableCell><TableCell>{({ready:'جاهز',invalid:'غير صالح',duplicate:'مكرر'} as Record<string,string>)[r.status]} {r.errors.join('، ')}</TableCell></TableRow>)}</TableBody></Table><button onClick={download}>تنزيل تقرير المراجعة بكل الصفوف الأصلية</button><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>راجعت المعاينة وأوافق على إدخال الصفوف الجاهزة فقط</label><button disabled={busy||!confirmed} onClick={()=>void run('commit')}>تأكيد الاستيراد</button></>}
 </section>;
}
