import {getAdmin as getChatGPTUser} from '@/lib/admin';
import {crmDb} from '@/lib/crm-db';
import data from '@/data/properties.json';
import {z} from 'zod';
export const dynamic='force-dynamic';
const schema=z.object({id:z.string().uuid(),name:z.string().trim().min(2).max(100),phone:z.string().trim().regex(/^[+\d\s()-]{7,22}$/),propertyId:z.string().refine(id=>data.some(p=>p.id===id)),notes:z.string().max(3000).default(''),stage:z.enum(['new','contacted','viewing','negotiation','won','closed']).default('new'),followUp:z.string().refine(v=>v===''||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&new Date(v).toISOString().slice(0,10)===v)).default('')});
export async function GET(){const u=await getChatGPTUser();if(!u)return Response.json({error:'يجب تسجيل الدخول'},{status:401});try{const r=await crmDb().prepare('SELECT * FROM leads WHERE owner=? ORDER BY created_at DESC').bind(u.userId).all();return Response.json(r.results,{headers:{'Cache-Control':'no-store'}})}catch(e){console.error('Lead load failed',e);return Response.json({error:'تعذر تحميل العملاء. حاول مجددًا.'},{status:503})}}
async function write(req:Request,update:boolean){const u=await getChatGPTUser();if(!u)return Response.json({error:'يجب تسجيل الدخول'},{status:401});if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'طلب غير مسموح'},{status:403});let input;try{const raw=await req.text();if(raw.length>12000)return Response.json({error:'الطلب أكبر من المسموح'},{status:413});input=schema.safeParse(JSON.parse(raw));}catch{return Response.json({error:'بيانات غير صالحة'},{status:400})}if(!input.success)return Response.json({error:'راجع الاسم ورقم الجوال والعقار والتاريخ'},{status:400});const v=input.data;const now=new Date().toISOString();try{if(update){const r=await crmDb().prepare('UPDATE leads SET name=?,phone=?,property_id=?,stage=?,notes=?,follow_up=?,updated_at=? WHERE id=? AND owner=?').bind(v.name,v.phone,v.propertyId,v.stage,v.notes,v.followUp,now,v.id,u.userId).run();if(!r.meta.changes)return Response.json({error:'الطلب غير موجود'},{status:404})}else{const old=await crmDb().prepare('SELECT owner FROM leads WHERE id=?').bind(v.id).first<{owner:string}>();if(old&&old.owner!==u.userId)return Response.json({error:'معرف مستخدم مسبقًا'},{status:409});if(!old)await crmDb().prepare('INSERT INTO leads(id,owner,name,phone,property_id,stage,notes,follow_up,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(v.id,u.userId,v.name,v.phone,v.propertyId,v.stage,v.notes,v.followUp,now,now).run()}return Response.json({ok:true,id:v.id})}catch(e){console.error('Lead save failed',e);return Response.json({error:'تعذر الحفظ. بياناتك باقية؛ حاول مجددًا.'},{status:503})}}
export async function POST(req:Request){return write(req,false)}
export async function PATCH(req:Request){return write(req,true)}
