'use client';
import {useState} from 'react';
import data from '@/data/properties.json';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export const stages:Record<string,string>={new:'جديد',contacted:'تم التواصل',viewing:'موعد معاينة',negotiation:'تفاوض',won:'تمت الصفقة',closed:'مغلق'};
export type Lead={id:string;name:string;phone:string;property_id:string;stage:string;notes:string;follow_up:string;created_at?:string};
export default function LeadForm({propertyId,initial,onSaved}:{propertyId?:string;initial?:Lead;onSaved?:()=>void}){const [name,setName]=useState(initial?.name||'');const [phone,setPhone]=useState(initial?.phone||'');const [prop,setProp]=useState(initial?.property_id||propertyId||data[0].id);const [stage,setStage]=useState(initial?.stage||'new');const [notes,setNotes]=useState(initial?.notes||'');const [date,setDate]=useState(initial?.follow_up||'');const [id]=useState(()=>initial?.id||crypto.randomUUID());const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [done,setDone]=useState(false);
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/leads',{method:initial?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,name,phone,propertyId:prop,stage,notes,followUp:date})});const v=await r.json() as {error?:string};if(!r.ok)throw Error(v.error);setDone(true);setMessage('تم حفظ الطلب في لوحة العملاء.');onSaved?.()}catch(e){setMessage(e instanceof Error?e.message:'تعذر الحفظ')}finally{setBusy(false)}}
return <form className="fields" onSubmit={submit}><label>الاسم<input required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label>رقم الجوال<input required type="tel" dir="ltr" maxLength={22} value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel"/></label>{!propertyId&&<label>العقار<Select value={prop} onValueChange={setProp} dir="rtl"><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{data.map(p=><SelectItem key={p.id} value={p.id}>{p.title}</SelectItem>)}</SelectContent></Select></label>}{!propertyId&&<><label>مرحلة الطلب<Select value={stage} onValueChange={setStage} dir="rtl"><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(stages).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></label><label>المتابعة القادمة<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></>}<label>ملاحظات<textarea rows={3} maxLength={3000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="primary" disabled={busy||done}>{busy?'جارٍ الحفظ…':done?'تم الحفظ':initial?'حفظ التحديث':'حفظ طلب الاهتمام'}</button>{message&&<p role="status" className={done?'success':'error'}>{message}</p>}</form>}
