import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync('.sites-runtime',{recursive:true});
const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync('drizzle/0000_overrated_beyonder.sql','utf8').replaceAll('--> statement-breakpoint',''));
globalThis.qaIdentity=null;
globalThis.qaDB={prepare(sql){let values=[];return {bind(...v){values=v;return this},async all(){return {results:sqlite.prepare(sql).all(...values)}},async first(){return sqlite.prepare(sql).get(...values)||null},async run(){const r=sqlite.prepare(sql).run(...values);return {meta:{changes:r.changes}}}}}};
await build({entryPoints:['app/api/leads/route.ts'],outfile:'.sites-runtime/test-api.cjs',bundle:true,platform:'node',format:'cjs',plugins:[{name:'test-environment',setup(b){b.onResolve({filter:/chatgpt-auth$/},()=>({path:'identity',namespace:'test'}));b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'db',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},args=>({contents:args.path==='identity'?'export async function getChatGPTUser(){return globalThis.qaIdentity}':'export const env={DB:globalThis.qaDB}',loader:'js'}))}}]});
const require=createRequire(import.meta.url);const api=require('../.sites-runtime/test-api.cjs');const property=JSON.parse(readFileSync('data/properties.json','utf8'))[0];
const make=(v,origin='https://sas.test')=>new Request('https://sas.test/api/leads',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(v)});
assert.equal((await api.GET()).status,401);
globalThis.qaIdentity={userId:'other',email:'other@example.invalid'};assert.equal((await api.GET()).status,401);
globalThis.qaIdentity={userId:'local_admin',email:'sasalthra.sa@gmail.com'};assert.equal((await api.GET()).status,401);
globalThis.qaIdentity={userId:'verified-test-admin',email:'sasalthra.sa@gmail.com'};
const v={id:crypto.randomUUID(),name:'عميل اختبار',phone:'+966500000000',propertyId:property.id,stage:'new',notes:'test',followUp:'2026-10-01'};
assert.equal((await api.POST(make(v))).status,200);assert.equal((await api.POST(make(v))).status,200);
let list=await (await api.GET()).json();assert.equal(list.length,1);
v.stage='viewing';assert.equal((await api.PATCH(make(v))).status,200);list=await (await api.GET()).json();assert.equal(list[0].stage,'viewing');
assert.equal((await api.POST(make({...v,propertyId:'bad'}))).status,400);
assert.equal((await api.POST(make(v,'https://evil.invalid'))).status,403);
globalThis.qaIdentity={userId:'other',email:'wrong@example.invalid'};assert.equal((await api.PATCH(make(v))).status,401);
const result={admin_allowlist:'passed',anonymous_rejected:true,other_email_rejected:true,local_identity_rejected:true,create_read_update:'passed',idempotency:'passed',invalid_property_rejected:true,cross_origin_rejected:true,scope:'Real API handlers and SQL in memory with mocked trusted platform identity. Live identity provider MFA was not tested or configured.'};
writeFileSync('qa-results.json',JSON.stringify(result,null,2));console.log(result);sqlite.close();
