// Isolated report policy/SQL regression suite. Never reads .env or opens a network connection.
import assert from 'node:assert/strict';
import {existsSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createRequire} from 'node:module';
import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import {assertCollationSafe, sqliteReportSql} from './sqlite-report-sql.mjs';
assert.ok(existsSync('lib/reports.ts'),'Reports engine must exist');
const out=mkdtempSync(join(tmpdir(),'sas-reports-'));
try {
 await build({entryPoints:['lib/reports.ts'],outfile:join(out,'reports.cjs'),bundle:true,platform:'node',format:'cjs',external:['mysql2/promise']});
 const {parseReportFilters,readReport,readReportDashboard,readAssignmentCounts,reportCsv,propertyNeighborhood,buildPropertiesSnapshot,readClientsSnapshot,readReportSnapshots,leadMatchesReportFilters}=createRequire(import.meta.url)(join(out,'reports.cjs'));
 const sql=new DatabaseSync(':memory:');
 sql.function('JSON_UNQUOTE',v=>v);
 const bounded=parseReportFilters(new URLSearchParams(),new Date('2026-09-15T22:30:00.000Z'));
 assert.equal(bounded.from,'2026-08-18','default starts 30 Riyadh calendar days inclusive');
 assert.equal(bounded.to,'2026-09-16','default ends on current Riyadh day');
 assert.throws(()=>parseReportFilters(new URLSearchParams('funding=bank\nleak')),/مرشح|صالح/);
 assert.throws(()=>parseReportFilters(new URLSearchParams('unknown=value')),/مرشح|معروف/);
 sql.exec(`CREATE TABLE leads(id TEXT,owner TEXT,created_by TEXT,assigned_to TEXT,field_assigned_to TEXT,name TEXT,property_id TEXT,property_other TEXT,source TEXT,stage TEXT,follow_up TEXT,created_at TEXT,updated_at TEXT);
 CREATE TABLE crm_users(id TEXT,name TEXT,role TEXT,active INTEGER,created_at TEXT);
 INSERT INTO crm_users VALUES ('alice','Alice','sales',1,'2026-01-01'),('bob','Bob','sales',1,'2026-01-01');`);
 const put=sql.prepare('INSERT INTO leads VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');
 for(const [id,owner,stamp,stage] of [['a','alice','2026-09-01T00:00:00.000Z','new'],['b','bob','2026-09-30T23:59:59.999Z','won'],['c','alice','2026-10-01T00:00:00.000Z','new']])put.run(id,owner,owner,owner,'',id,'p','',"web' OR 1=1 --",stage,'2026-09-10',stamp,stamp);
 const db={prepare(query){assert.match(query.trim(),/^SELECT/,'read-only SQL');assertCollationSafe(query);const runnable=sqliteReportSql(query);let args=[];return {bind(...v){args=v;return this;},async all(){return {results:sql.prepare(runnable).all(...args)};}};}};
 const admin={userId:'root',role:'admin'},alice={userId:'alice',role:'sales'};
 const filters=parseReportFilters(new URLSearchParams('from=2026-09-01&to=2026-09-30'));
 let report=await readReport(db,admin,'leads',filters);
 assert.equal(report.total,1,'Riyadh calendar endpoint excludes UTC timestamps after 21:00');
 assert.equal(report.groups.stage.find(x=>x.label==='عميل جديد').count,1);
 assert.deepEqual(report.groups.stage.map(x=>x.label),['عميل جديد']);
 report=await readReport(db,alice,'leads',filters);assert.equal(report.total,1,'owner isolation applies to totals');assert.equal(report.rows[0].id,'a');
 assert.throws(()=>parseReportFilters(new URLSearchParams('from=2026-02-30')),/date|تاريخ/);
 assert.throws(()=>parseReportFilters(new URLSearchParams('from=2026-10-01&to=2026-09-01')),/date|تاريخ/);
 await assert.rejects(()=>readReport(db,alice,'leads',{...filters,employee:'bob'}),/صلاحية|مسموح/);
 await assert.rejects(()=>readReport(db,alice,'transactions',filters),/صلاحية|مسموح/);
 assert.equal((await readReport(db,admin,'leads',{...filters,source:"web' OR 1=1 --"})).total,1,'filter values are bound');
 // Trend: continuous daily series over the filtered window, bucketed by Riyadh day, zero-filled, and scope-respecting.
 {
  const trendReport=await readReport(db,admin,'leads',filters);
  assert.ok(trendReport.trend,'leads report exposes a trend series');
  assert.equal(trendReport.trend.points.length,30,'trend covers every day of the 30-day window');
  assert.equal(trendReport.trend.points[0].day,'2026-09-01');
  assert.equal(trendReport.trend.points.at(-1).day,'2026-09-30');
  assert.equal(trendReport.trend.points[0].count,1,'the in-window lead lands on its Riyadh day');
  assert.equal(trendReport.trend.points.reduce((n,p)=>n+p.count,0),trendReport.total,'trend total equals the authorized report total');
  assert.ok(trendReport.trend.points.some(p=>p.count===0),'days without records are zero-filled, not dropped');
  const scoped=await readReport(db,alice,'leads',filters);
  assert.equal(scoped.trend.points.reduce((n,p)=>n+p.count,0),scoped.total,'trend never leaks records outside the actor scope');
  const snapshot=await readReport(db,admin,'users',filters);
  assert.equal(snapshot.trend,undefined,'snapshot reports without a date basis expose no trend');
 }
 const csv=reportCsv({columns:[{key:'value',label:'Value'}],rows:[{value:' =HYPERLINK("bad")'},{value:'\t+CMD'},{value:'سليم,\n"نص"'}]});
 assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes("' =HYPERLINK"));assert.ok(csv.includes("'\t+CMD"));assert.ok(csv.includes('""نص""'));
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM leads').get().n,3);
 // System snapshots: no date window, auth scope, interested/not_interested pairing, neighborhoods.
 put.run('d','alice','alice','alice','','d','p','','web','not_interested','2026-09-10','2025-01-01T00:00:00.000Z','2025-01-01T00:00:00.000Z');
 put.run('e','bob','bob','bob','','e','p','','web','viewing','2026-09-10','2025-06-01T00:00:00.000Z','2025-06-01T00:00:00.000Z');
 {
  const snap=await readClientsSnapshot(db,admin,{employee:''});
  assert.equal(snap.total,5,'snapshot ignores the default date window');
  assert.equal(snap.notInterested,1);
  assert.equal(snap.interested,4,'interested = all stages except not_interested');
  assert.ok(snap.byStage.some(s=>s.stage==='field_dispatch'&&s.label==='تفويج للميداني'));
  assert.deepEqual(snap.byStage.map(s=>s.stage),['new','field_dispatch','contract_signed','not_interested']);
  assert.equal(snap.byStage.some(s=>s.stage==='viewing'||s.label==='معاينة'),false);
  const aliceSnap=await readClientsSnapshot(db,alice,{employee:''});
  assert.equal(aliceSnap.total,3,'sales scope still applies without a date filter');
  assert.equal(aliceSnap.notInterested,1);
  assert.equal(propertyNeighborhood({address:'الروضة',title:'شقق حي النزهه'}),'الروضة');
  assert.equal(propertyNeighborhood({address:'',title:'فيلا حي النزهه مشروع'}),'النزهه');
  assert.equal(propertyNeighborhood({address:'  ',title:'بدون حي'}),'غير محدد');
  const props=buildPropertiesSnapshot([{id:'1',title:'فيلا حي النزهه',address:''},{id:'2',title:'x',address:'الروضة'},{id:'3',title:'y',address:''}]);
  assert.equal(props.total,3);
  assert.equal(props.byNeighborhood.find(n=>n.label==='النزهه').count,1);
  assert.equal(props.byNeighborhood.find(n=>n.label==='غير محدد').count,1);
  const wrapped=await readReportSnapshots(db,admin,{employee:''},[{id:'1',title:'فيلا حي النزهه',address:''}],e=>e instanceof Error?e.message:'fail');
  assert.equal(wrapped.clients.status,'ok');
  assert.equal(wrapped.properties.status,'ok');
  assert.equal(wrapped.properties.total,1);
 }
 put.run('won-row','alice','alice','alice','','won-row','p','','web','won','2026-09-10','2026-09-02T00:00:00.000Z','2026-09-02T00:00:00.000Z');
 {
  const wonView=await readReport(db,admin,'leads',filters);
  assert.equal(wonView.rows.find(r=>r.id==='won-row').stage,'وقع عقد');
  assert.equal(JSON.stringify(wonView).includes('مكسب'),false);
  assert.equal(wonView.groups.stage.some(g=>g.label==='won'||g.label==='مكسب'),false);
  const folded=await readClientsSnapshot(db,admin,{employee:''});
  assert.equal(folded.byStage.some(s=>s.stage==='won'||s.label==='مكسب'),false);
  assert.equal(folded.byStage.find(s=>s.stage==='contract_signed').label,'وقع عقد');
  assert.ok(folded.byStage.find(s=>s.stage==='contract_signed').count>=2);
  const alias=await readReport(db,admin,'leads',{...filters,stage:'مكسب'});
  assert.ok(alias.rows.some(r=>r.id==='won-row'));
 }
 sql.exec(`CREATE TABLE crm_transactions(id TEXT,lead_id TEXT,data TEXT,confirmed_due TEXT,updated_at TEXT,owner_commission TEXT,client_commission TEXT);
 CREATE TABLE hr_attendance(user_id TEXT,work_day TEXT,check_in TEXT,check_out TEXT,late_minutes INTEGER);
 CREATE TABLE hr_profiles(user_id TEXT,job_title TEXT,department TEXT,leave_balance TEXT,schedule TEXT,updated_at TEXT);
 CREATE TABLE crm_integrations(id TEXT,last_run TEXT,last_result TEXT,config TEXT DEFAULT '{}');`);
 const tx=sql.prepare('INSERT INTO crm_transactions (id,lead_id,data,confirmed_due,updated_at) VALUES (?,?,?,?,?)');
 tx.run('t1','a',JSON.stringify({brokerage:'0.10',debtPayer:'company',debtSettlement:'900000000000.01',balance:'-0.10'}),'900000000000.11','2026-09-01');
 tx.run('t2','b',JSON.stringify({brokerage:'0.20',debtPayer:'client',debtSettlement:'800.99',clientCollection:'0.10',balance:'-0.20'}),'0.20','2026-09-02');
 report=await readReport(db,admin,'transactions',filters);
 const metric=label=>report.metrics.find(m=>m.label.includes(label));
 assert.equal(metric('السعي — مدخل').value,'0.30');assert.equal(metric('المستحق المؤكد').value,'900000000000.31');
 assert.equal(metric('رصيد — يدوي').value,'-0.30');assert.equal(metric('تحصيل العميل للشركة').value,'0.10');assert.equal(metric('تحصيل العميل للشركة').missing,1);
 assert.equal(report.rows.find(r=>r.id==='t2').companyDebt,null);
 assert.equal(metric('إجمالي متحصلات').value,null,'unknown is not zero');
 sql.exec(`INSERT INTO hr_attendance VALUES ('alice','2026-09-01','2026-09-01T06:00:00Z','2026-09-01T14:00:00Z',7),('bob','2026-09-01','2026-09-01T06:00:00Z',NULL,0);
 INSERT INTO hr_profiles VALUES ('alice','Sales','Sales','12','{}','2026-09-01'),('bob','Private','Private','90','{}','2026-09-01');`);
 report=await readReport(db,alice,'attendance',filters);assert.equal(report.total,1);assert.equal(report.metrics[0].value,'8.00');
 assert.equal((await readReport(db,alice,'profiles',filters)).total,1);
 for(const role of ['sales','field','supervisor'])for(const reportId of ['transactions','users','imports','importRows','sheets','ai','audit'])await assert.rejects(()=>readReport(db,{...alice,role},reportId,filters),/صلاحية/);
 for(const role of ['sales','field','supervisor'])await assert.rejects(()=>readReport(db,{...alice,role},'leads',filters,{exporting:true}),/صلاحية/);
 sql.prepare('INSERT INTO crm_integrations (id,last_run,last_result) VALUES (?,?,?)').run('sheets','2026-09-02',JSON.stringify({inserted:2,duplicates:1,invalid:[{row:3,errors:['private']},{row:4,errors:['private']}]}));
 report=await readReport(db,admin,'sheets',filters);assert.equal(report.rows[0].health,'آخر تشغيل ناجح');assert.equal(report.rows[0].invalid,2);assert.ok(!JSON.stringify(report).includes('private'));
 sql.exec('ALTER TABLE crm_users ADD COLUMN username TEXT');
 sql.prepare('UPDATE crm_users SET username=? WHERE id=?').run('alice.user','alice');
 put.run('by-user','root','root','alice.user','','باسم المستخدم','p','','tiktok','contacted','2026-09-11','2026-09-11T00:00:00.000Z','2026-09-04T00:00:00.000Z');
 put.run('by-name','root','root','Alice','','بالاسم','p','','تيك توك','interested','2026-09-11','2026-09-11T00:00:00.000Z','2026-09-11T00:00:00.000Z');
 put.run('stale','alice','alice','alice','','قديم','p','','whatsapp','contacted','2026-09-01','2026-09-12T00:00:00.000Z','2026-09-01T00:00:00.000Z');
 put.run('fresh-wait','root','root','','','منتظر','p','','واتساب','new','','2026-09-10T00:00:00.000Z','2026-09-10T00:00:00.000Z');
 const aliased=await readReport(db,admin,'leads',{...filters,employee:'alice'});
 assert.ok(aliased.rows.some(r=>r.id==='by-user'),'username stored in assigned_to still matches the employee id');
 assert.equal(aliased.rows.find(r=>r.id==='by-user').sales,'Alice');
 assert.ok(aliased.rows.some(r=>r.id==='by-name'),'display name stored in assigned_to still matches the employee id');
 const combo=await readReport(db,admin,'leads',{...filters,employee:'alice',source:'tiktok',stage:'تم التواصل',pageSize:50});
 assert.ok(combo.rows.some(r=>r.id==='by-user'));
 await readReport(db,admin,'transactions',{...filters,employee:'alice'});
 await readReport(db,admin,'attendance',{...filters,employee:'alice'});
 await readReport(db,admin,'profiles',{...filters,employee:'alice'});
 const dash=await readReportDashboard(db,admin,{...filters,employee:''},new Date('2026-09-20T12:00:00.000Z'));
 assert.ok(dash.byStage.filter(s=>s.stage==='interested'&&s.label==='مهتم').length===1);
 assert.equal(dash.byStage.length>=16,true);
 assert.ok(dash.byStage.every(s=>Number.isInteger(s.pct)));
 const alicePerf=dash.employees.find(e=>e.id==='alice');
 assert.ok(alicePerf.assigned>=1);
 assert.equal(typeof alicePerf.completion,'number');
 assert.equal(alicePerf.contacted>=1,true);
 const tiktok=dash.sources.find(s=>s.key==='tiktok');
 assert.ok(tiktok&&tiktok.total>=2,'TikTok and تيك توك share one source');
 assert.ok(dash.sources.some(s=>s.key==='whatsapp'&&s.label==='واتساب'));
 assert.ok(dash.inactive>=1);
 assert.ok(dash.unassignedWaiting>=1);
 assert.ok(dash.overdue>=1);
 assert.ok(dash.alerts.some(a=>a.href.includes('inactive=1')));
 assert.ok(dash.alerts.some(a=>a.href.includes('waiting=1')));
 assert.ok(dash.alerts.some(a=>a.href.includes('overdue=1')&&a.href.includes('tab=leads')));
 assert.equal(dash.alerts.some(a=>/تصدير CSV/.test(a.message)),false);
 sql.prepare(`INSERT INTO crm_users (id,name,role,active,created_at,username) VALUES ('ohoud','عهود','sales',1,'2026-01-01','ohoud.user')`).run();
 const ohoudRows=[
  ['o1','root','root','ohoud','','o1','p','','tiktok','contacted','2026-09-01','2026-09-23T00:00:00.000Z','2026-09-23T00:00:00.000Z'],
  ['o2','root','root','ohoud.user','','o2','p','','website','contacted','','2026-10-07T18:00:00.000Z','2026-10-07T18:00:00.000Z'],
  ['o3','root','root','عهود','','o3','p','','tiktok','interested','','2026-09-25T00:00:00.000Z','2026-09-25T00:00:00.000Z'],
  ['o4','root','root','ohoud','','o4','p','','tiktok','contacted','2026-09-01','2026-09-22T12:00:00.000Z','2026-09-22T12:00:00.000Z'],
  ['o5','root','root','bob','','o5','p','','tiktok','contacted','','2026-09-24T00:00:00.000Z','2026-09-24T00:00:00.000Z'],
  ['o6','root','root','ohoud','','o6','p','','tiktok','won','2026-09-01','2026-09-28T00:00:00.000Z','2026-09-28T00:00:00.000Z'],
 ];
 for(const row of ohoudRows)put.run(...row);
 const comboFilters={...filters,from:'2026-09-23',to:'2026-10-07',employee:'ohoud',stage:'تم التواصل',source:'',pageSize:50};
 const ohoudDash=await readReportDashboard(db,admin,comboFilters,new Date('2026-10-07T12:00:00.000Z'));
 assert.equal(ohoudDash.employees.length,1,'choosing one employee leaves a single employee row');
 assert.equal(ohoudDash.employees[0].name,'عهود');
 assert.equal(ohoudDash.total,2,'employee + stage + period');
 assert.equal(ohoudDash.scheduled,1);
 assert.equal(ohoudDash.signed,0);
 assert.equal(ohoudDash.byStage.filter(s=>s.count>0).every(s=>s.stage==='contacted'),true);
 assert.equal(ohoudDash.sources.reduce((n,s)=>n+s.total,0),ohoudDash.total);
 const tokens=['ohoud','عهود','ohoud.user'];
 const listed=sql.prepare('SELECT * FROM leads').all().filter(row=>leadMatchesReportFilters(row,{from:comboFilters.from,to:comboFilters.to,stage:comboFilters.stage,employeeTokens:tokens,sourceExact:true,today:'2026-10-07',nowMs:Date.parse('2026-10-07T12:00:00.000Z')}));
 assert.equal(listed.length,ohoudDash.total,'drill-down count equals the filtered card count');
 const broad=await readReport(db,admin,'leads',{...comboFilters,stage:''});
 assert.ok(broad.rows.some(r=>r.id==='o1'),'assigned_to id matches');
 assert.ok(broad.rows.some(r=>r.id==='o2'),'assigned_to username matches');
 assert.ok(broad.rows.some(r=>r.id==='o3'),'assigned_to display name matches');
 assert.equal(broad.rows.some(r=>r.id==='o4'),false,'registration day before the period is excluded');
 assert.equal(broad.rows.some(r=>r.id==='o5'),false);
 assert.equal(broad.total,4);
 assert.equal((await readReportDashboard(db,admin,{...comboFilters,stage:''},new Date('2026-10-07T12:00:00.000Z'))).signed,1);
 sql.exec(`CREATE TABLE lead_activity(id TEXT,lead_id TEXT,action TEXT,details TEXT,created_at TEXT); ALTER TABLE leads ADD COLUMN assigned_at TEXT;`);
 sql.prepare('INSERT INTO lead_activity VALUES (?,?,?,?,?)').run('act-o1','o1','assigned',JSON.stringify({assignedTo:'ohoud'}),'2026-10-07T10:00:00.000Z');
 sql.prepare('INSERT INTO lead_activity VALUES (?,?,?,?,?)').run('act-name','ghost','assigned',JSON.stringify({assignedTo:'عهود'}),'2026-10-07T11:00:00.000Z');
 sql.prepare('INSERT INTO lead_activity VALUES (?,?,?,?,?)').run('act-old','o4','assigned',JSON.stringify({assignedTo:'ohoud'}),'2026-09-01T10:00:00.000Z');
 sql.prepare(`UPDATE leads SET assigned_at=?, created_at=? WHERE id='o5'`).run('2026-10-07T10:00:00.000Z','2026-09-24T00:00:00.000Z');
 const assignedToday=await readAssignmentCounts(db,'2026-10-07','2026-10-07','');
 assert.equal(assignedToday.unavailable,false);
 assert.equal(assignedToday.total,3,'activity id, activity display name, and assigned_at; created_at is not an assignment');
 const assignedOhoud=await readAssignmentCounts(db,'2026-10-07','2026-10-07','ohoud');
 assert.equal(assignedOhoud.total,2,'username and display name resolve to the same employee');
 assert.equal(assignedOhoud.byEmployee.every(row=>row.name==='عهود'),true);
 const legacy=await readReport(db,admin,'transactions',filters);
 assert.equal(legacy.rows.find(r=>r.id==='t1').brokerage,'0.10');
 assert.equal(legacy.rows.find(r=>r.id==='t1').commissionNote,'0.10');
 assert.equal(legacy.rows.find(r=>r.id==='t1').ownerCommission,null);
 assert.match(String(legacy.rows.find(r=>r.id==='t1').updated_at),/^\d{4}-\d{2}-\d{2} \d{2}:\d{2} [صم]$/);
 assert.equal(legacy.columns.some(c=>c.key==='ownerCommission'&&c.label==='العمولة من المالك'),true);
 assert.equal(legacy.columns.some(c=>c.key==='totalCommission'),true);
 assert.equal(legacy.columns.some(c=>c.label==='ملاحظة عمولة سابقة'),true);
 sql.prepare(`UPDATE crm_transactions SET owner_commission=?, client_commission=? WHERE id='t2'`).run('1000','250.50');
 const split=await readReport(db,admin,'transactions',filters);
 const splitRow=split.rows.find(r=>r.id==='t2');
 assert.equal(splitRow.ownerCommission,'1000');
 assert.equal(splitRow.clientCommission,'250.50');
 assert.equal(splitRow.totalCommission,'1250.50');
 assert.equal(split.metrics.find(m=>m.label.includes('إجمالي العمولة')).value,'1250.50');
 sql.close();console.log('PASS reports date bounds, aggregation, scope, bound SQL, CSV injection and read-only execution');
} finally {rmSync(out,{recursive:true,force:true});}
