// Isolated report policy/SQL regression suite. Never reads .env or opens a network connection.
import assert from 'node:assert/strict';
import {existsSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createRequire} from 'node:module';
import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
assert.ok(existsSync('lib/reports.ts'),'Reports engine must exist');
const out=mkdtempSync(join(tmpdir(),'sas-reports-'));
try {
 await build({entryPoints:['lib/reports.ts'],outfile:join(out,'reports.cjs'),bundle:true,platform:'node',format:'cjs',external:['mysql2/promise']});
 const {parseReportFilters,readReport,reportCsv}=createRequire(import.meta.url)(join(out,'reports.cjs'));
 const sql=new DatabaseSync(':memory:');
 sql.function('CONVERT_TZ',(value,from,to)=>{assert.equal(from,'+00:00');assert.equal(to,'+03:00');if(value==null)return null;const text=String(value).replace(' ','T');const parsed=Date.parse(text.endsWith('Z')?text:text+'Z');return new Date(parsed+3*60*60*1000).toISOString().replace('T',' ');});
 const bounded=parseReportFilters(new URLSearchParams(),new Date('2026-09-15T22:30:00.000Z'));
 assert.equal(bounded.from,'2026-08-18','default starts 30 Riyadh calendar days inclusive');
 assert.equal(bounded.to,'2026-09-16','default ends on current Riyadh day');
 assert.throws(()=>parseReportFilters(new URLSearchParams('funding=bank\nleak')),/مرشح|صالح/);
 assert.throws(()=>parseReportFilters(new URLSearchParams('unknown=value')),/مرشح|معروف/);
 sql.exec(`CREATE TABLE leads(id TEXT,owner TEXT,created_by TEXT,assigned_to TEXT,field_assigned_to TEXT,name TEXT,property_id TEXT,property_other TEXT,source TEXT,stage TEXT,follow_up TEXT,created_at TEXT,updated_at TEXT);
 CREATE TABLE crm_users(id TEXT,name TEXT,role TEXT,active INTEGER,created_at TEXT);
 INSERT INTO crm_users VALUES ('alice','Alice','sales',1,'2026-01-01'),('bob','Bob','sales',1,'2026-01-01');`);
 const put=sql.prepare('INSERT INTO leads VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');
 for(const [id,owner,stamp,stage] of [['a','alice','2026-09-01T00:00:00.000Z','new'],['b','bob','2026-09-30T23:59:59.999Z','won'],['c','alice','2026-10-01T00:00:00.000Z','new']])put.run(id,owner,owner,owner,'',id,'p','',"web' OR 1=1 --",stage,'2026-09-10',stamp,stamp);
 const db={prepare(query){assert.match(query.trim(),/^SELECT/,'read-only SQL');let args=[];return {bind(...v){args=v;return this;},async all(){return {results:sql.prepare(query).all(...args)};}};}};
 const admin={userId:'root',role:'admin'},alice={userId:'alice',role:'sales'};
 const filters=parseReportFilters(new URLSearchParams('from=2026-09-01&to=2026-09-30'));
 let report=await readReport(db,admin,'leads',filters);
 assert.equal(report.total,1,'Riyadh calendar endpoint excludes UTC timestamps after 21:00');
 assert.equal(report.groups.stage.find(x=>x.label==='new').count,1);
 report=await readReport(db,alice,'leads',filters);assert.equal(report.total,1,'owner isolation applies to totals');assert.equal(report.rows[0].id,'a');
 assert.throws(()=>parseReportFilters(new URLSearchParams('from=2026-02-30')),/date|تاريخ/);
 assert.throws(()=>parseReportFilters(new URLSearchParams('from=2026-10-01&to=2026-09-01')),/date|تاريخ/);
 await assert.rejects(()=>readReport(db,alice,'leads',{...filters,employee:'bob'}),/صلاحية|مسموح/);
 await assert.rejects(()=>readReport(db,alice,'transactions',filters),/صلاحية|مسموح/);
 assert.equal((await readReport(db,admin,'leads',{...filters,source:"web' OR 1=1 --"})).total,1,'filter values are bound');
 // Trend: continuous daily series over the filtered window, bucketed by Riyadh day, zero-filled, and scope-respecting.
 {
  const trendReport=await readReport(db,admin,'leads',filters);
  assert.ok(trendReport.trend,'leads report exposes a trend series');
  assert.equal(trendReport.trend.points.length,30,'trend covers every day of the 30-day window');
  assert.equal(trendReport.trend.points[0].day,'2026-09-01');
  assert.equal(trendReport.trend.points.at(-1).day,'2026-09-30');
  assert.equal(trendReport.trend.points[0].count,1,'the in-window lead lands on its Riyadh day');
  assert.equal(trendReport.trend.points.reduce((n,p)=>n+p.count,0),trendReport.total,'trend total equals the authorized report total');
  assert.ok(trendReport.trend.points.some(p=>p.count===0),'days without records are zero-filled, not dropped');
  const scoped=await readReport(db,alice,'leads',filters);
  assert.equal(scoped.trend.points.reduce((n,p)=>n+p.count,0),scoped.total,'trend never leaks records outside the actor scope');
  const snapshot=await readReport(db,admin,'users',filters);
  assert.equal(snapshot.trend,undefined,'snapshot reports without a date basis expose no trend');
 }
 const csv=reportCsv({columns:[{key:'value',label:'Value'}],rows:[{value:' =HYPERLINK("bad")'},{value:'\t+CMD'},{value:'سليم,\n"نص"'}]});
 assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes("' =HYPERLINK"));assert.ok(csv.includes("'\t+CMD"));assert.ok(csv.includes('""نص""'));
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM leads').get().n,3);
 sql.exec(`CREATE TABLE crm_transactions(id TEXT,lead_id TEXT,data TEXT,confirmed_due TEXT,updated_at TEXT);
 CREATE TABLE hr_attendance(user_id TEXT,work_day TEXT,check_in TEXT,check_out TEXT,late_minutes INTEGER);
 CREATE TABLE hr_profiles(user_id TEXT,job_title TEXT,department TEXT,leave_balance TEXT,schedule TEXT,updated_at TEXT);
 CREATE TABLE crm_integrations(id TEXT,last_run TEXT,last_result TEXT,config TEXT DEFAULT '{}');`);
 const tx=sql.prepare('INSERT INTO crm_transactions VALUES (?,?,?,?,?)');
 tx.run('t1','a',JSON.stringify({brokerage:'0.10',debtPayer:'company',debtSettlement:'900000000000.01',balance:'-0.10'}),'900000000000.11','2026-09-01');
 tx.run('t2','b',JSON.stringify({brokerage:'0.20',debtPayer:'client',debtSettlement:'800.99',clientCollection:'0.10',balance:'-0.20'}),'0.20','2026-09-02');
 report=await readReport(db,admin,'transactions',filters);
 const metric=label=>report.metrics.find(m=>m.label.includes(label));
 assert.equal(metric('السعي — مدخل').value,'0.30');assert.equal(metric('المستحق المؤكد').value,'900000000000.31');
 assert.equal(metric('رصيد — يدوي').value,'-0.30');assert.equal(metric('تحصيل العميل للشركة').value,'0.10');assert.equal(metric('تحصيل العميل للشركة').missing,1);
 assert.equal(report.rows.find(r=>r.id==='t2').companyDebt,null);
 assert.equal(metric('إجمالي متحصلات').value,null,'unknown is not zero');
 sql.exec(`INSERT INTO hr_attendance VALUES ('alice','2026-09-01','2026-09-01T06:00:00Z','2026-09-01T14:00:00Z',7),('bob','2026-09-01','2026-09-01T06:00:00Z',NULL,0);
 INSERT INTO hr_profiles VALUES ('alice','Sales','Sales','12','{}','2026-09-01'),('bob','Private','Private','90','{}','2026-09-01');`);
 report=await readReport(db,alice,'attendance',filters);assert.equal(report.total,1);assert.equal(report.metrics[0].value,'8.00');
 assert.equal((await readReport(db,alice,'profiles',filters)).total,1);
 for(const role of ['sales','field','supervisor'])for(const reportId of ['transactions','users','imports','importRows','sheets','ai','audit'])await assert.rejects(()=>readReport(db,{...alice,role},reportId,filters),/صلاحية/);
 for(const role of ['sales','field','supervisor'])await assert.rejects(()=>readReport(db,{...alice,role},'leads',filters,{exporting:true}),/صلاحية/);
 sql.prepare('INSERT INTO crm_integrations (id,last_run,last_result) VALUES (?,?,?)').run('sheets','2026-09-02',JSON.stringify({inserted:2,duplicates:1,invalid:[{row:3,errors:['private']},{row:4,errors:['private']}]}));
 report=await readReport(db,admin,'sheets',filters);assert.equal(report.rows[0].health,'آخر تشغيل ناجح');assert.equal(report.rows[0].invalid,2);assert.ok(!JSON.stringify(report).includes('private'));
 sql.close();console.log('PASS reports date bounds, aggregation, scope, bound SQL, CSV injection and read-only execution');
} finally {rmSync(out,{recursive:true,force:true});}
